In [4]:
#import libraries

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder

In [36]:
# input the dataset

df = pd.read_csv('mnist_dataset.csv')
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [25]:
# Create an instance of the OneHotEncoder class

encoder = OneHotEncoder()

In [26]:
y_encoded = encoder.fit_transform(y.values.reshape(-1, 1)).toarray()

In [27]:
print(type(y_encoded))

<class 'numpy.ndarray'>


In [33]:
 print("y shape:", y_encoded.shape)

y shape: (6400, 10)


In [28]:
print(y_encoded)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [37]:
# Train Test Split
 
x_train, x_test_val, y_train, y_test_val = train_test_split(x, y_encoded, test_size=0.2, random_state=34)
x_test, x_val, y_test, y_val = train_test_split(x_test_val, y_test_val, test_size=0.5, random_state=34)

In [39]:
target = "label"

In [40]:
# add targets as FIRST COLUMN

x_train.insert(0, target, y_train.tolist())
x_test.insert(0, target, y_test.tolist())
x_val.insert(0, target, y_val.tolist())

In [41]:
# write results locally

output_train_path = '/content/train'
output_test_path = '/content/test/'
output_val_path = '/content/val/'

x_train.to_csv(f'{output_train_path}/preprocessing_train_output.csv', index=False, header=False)
x_test.to_csv(f'{output_test_path}/preprocessing_test_output.csv', index=False, header=False)
x_val.to_csv(f'{output_val_path}/preprocessing_val_output.csv', index=False, header=False)

In [42]:
# Read train data from "preprocessing_train_output.csv" file

df_train = pd.read_csv('/content/train/preprocessing_train_output.csv')
x_train = df_train.iloc[:,1:].values
y_train = df_train.iloc[:,0].values

In [45]:
print(x_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
print(y_train)

['[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]'
 '[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]'
 '[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]' ...
 '[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]'
 '[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]'
 '[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]']


In [47]:
# Read test data from "preprocessing_test_output.csv" file

df_test = pd.read_csv('/content/test/preprocessing_test_output.csv')
x_test = df_test.iloc[:,1:].values
y_test = df_test.iloc[:,0].values

In [48]:
# define params

batch_size = 64
epochs = 10
learning_rate = 0.01
    
# define and compile the model

model = Sequential()
model.add(Dense(128, input_dim=784, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [53]:
optimizer = Adam(learning_rate=learning_rate)

In [54]:
# model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [55]:
# train

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test))

Epoch 1/10


ValueError: ignored